Give up on 3.0 and require Swift 3.1+
error: type 'JoinCalculationError' cannot be nested in generic type 'CodeRelationshipBase'
  enum JoinCalculationError : Swift.Error {
       ^
<unknown>:0: error: build had 1 command failures